<?php
$serviceContainer = \Propel\Runtime\Propel::getServiceContainer();
$serviceContainer->initDatabaseMaps(array (
  'default' => 
  array (
    0 => '\\DB\\Map\\AccessTableMap',
    1 => '\\DB\\Map\\GroupsTableMap',
    2 => '\\DB\\Map\\GroupsVersionTableMap',
    3 => '\\DB\\Map\\HouseTableMap',
    4 => '\\DB\\Map\\HouseVersionTableMap',
    5 => '\\DB\\Map\\MaterialTableMap',
    6 => '\\DB\\Map\\MaterialVersionTableMap',
    7 => '\\DB\\Map\\ProjectRoleTableMap',
//    8 => '\\DB\\Map\\ProjectRoleVersionTableMap',
    9 => '\\DB\\Map\\ProjectTableMap',
    10 => '\\DB\\Map\\ProjectVersionTableMap',
    11 => '\\DB\\Map\\RoleTableMap',
    12 => '\\DB\\Map\\StageMaterialTableMap',
    13 => '\\DB\\Map\\StageMaterialVersionTableMap',
    14 => '\\DB\\Map\\StageTableMap',
    15 => '\\DB\\Map\\StageTechnicTableMap',
    16 => '\\DB\\Map\\StageTechnicVersionTableMap',
    17 => '\\DB\\Map\\StageVersionTableMap',
    18 => '\\DB\\Map\\StageWorkTableMap',
    19 => '\\DB\\Map\\StageWorkVersionTableMap',
    20 => '\\DB\\Map\\SubprojectTableMap',
    21 => '\\DB\\Map\\SubprojectVersionTableMap',
    22 => '\\DB\\Map\\TechnicTableMap',
    23 => '\\DB\\Map\\TechnicVersionTableMap',
    24 => '\\DB\\Map\\UnitTableMap',
    25 => '\\DB\\Map\\UsersConfirmationsTableMap',
    26 => '\\DB\\Map\\UsersRememberedTableMap',
    27 => '\\DB\\Map\\UsersResetsTableMap',
    28 => '\\DB\\Map\\UsersTableMap',
    29 => '\\DB\\Map\\UsersThrottlingTableMap',
    30 => '\\DB\\Map\\WorkMaterialTableMap',
    31 => '\\DB\\Map\\WorkMaterialVersionTableMap',
    32 => '\\DB\\Map\\WorkTableMap',
    33 => '\\DB\\Map\\WorkTechnicTableMap',
    34 => '\\DB\\Map\\WorkTechnicVersionTableMap',
    35 => '\\DB\\Map\\WorkVersionTableMap',
  ),
));
