<?php
$serviceContainer = \Propel\Runtime\Propel::getServiceContainer();
$serviceContainer->initDatabaseMaps(array (
  'default' => 
  array (
    0 => '\\DB\\Map\\ObjGroupTableMap',
    1 => '\\DB\\Map\\ObjGroupVersionTableMap',
    2 => '\\DB\\Map\\ObjHouseTableMap',
    3 => '\\DB\\Map\\ObjHouseVersionTableMap',
    4 => '\\DB\\Map\\ObjProjectTableMap',
    5 => '\\DB\\Map\\ObjProjectVersionTableMap',
    6 => '\\DB\\Map\\ObjStageMaterialTableMap',
    7 => '\\DB\\Map\\ObjStageMaterialVersionTableMap',
    8 => '\\DB\\Map\\ObjStageTableMap',
    9 => '\\DB\\Map\\ObjStageTechnicTableMap',
    10 => '\\DB\\Map\\ObjStageTechnicVersionTableMap',
    11 => '\\DB\\Map\\ObjStageVersionTableMap',
    12 => '\\DB\\Map\\ObjStageWorkTableMap',
    13 => '\\DB\\Map\\ObjStageWorkVersionTableMap',
    14 => '\\DB\\Map\\ObjSubprojectTableMap',
    15 => '\\DB\\Map\\ObjSubprojectVersionTableMap',
    16 => '\\DB\\Map\\ProjectRoleTableMap',
    17 => '\\DB\\Map\\StaticFileTableMap',
    18 => '\\DB\\Map\\UserRoleTableMap',
    19 => '\\DB\\Map\\UsersConfirmationsTableMap',
    20 => '\\DB\\Map\\UsersRememberedTableMap',
    21 => '\\DB\\Map\\UsersResetsTableMap',
    22 => '\\DB\\Map\\UsersTableMap',
    23 => '\\DB\\Map\\UsersThrottlingTableMap',
    24 => '\\DB\\Map\\VolMaterialTableMap',
    25 => '\\DB\\Map\\VolMaterialVersionTableMap',
    26 => '\\DB\\Map\\VolTechnicTableMap',
    27 => '\\DB\\Map\\VolTechnicVersionTableMap',
    28 => '\\DB\\Map\\VolUnitTableMap',
    29 => '\\DB\\Map\\VolWorkMaterialTableMap',
    30 => '\\DB\\Map\\VolWorkMaterialVersionTableMap',
    31 => '\\DB\\Map\\VolWorkTableMap',
    32 => '\\DB\\Map\\VolWorkTechnicTableMap',
//    33 => '\\DB\\Map\\VolWorkTechnicVersionTableMap',
//    34 => '\\DB\\Map\\VolWorkVersionTableMap',
  ),
));
